server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: calculator-service
            uri: lb://calculator-service
            predicates:
              - Path=/api/v1/calculators/**
          - id: invierte-ya-service
            uri: lb://invierte-ya-service
            predicates:
              - Path=/api/v1/**