server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: calculator-service
  profiles:
    active: develop
  config:
    import: configserver:https://config-server-2024-9adfd2ef5224.herokuapp.com #http://localhost:8888